name: Trigger Render Deployment
on:
  push:
    branches:
      - main
  pull_request:    
    branches: [main]
    types: [opened, synchronize]
  
jobs:
  main:
    name: Deploy to Render
    runs-on: ubuntu-latest
    environment: Render
    steps:
      - name: Debug service ID format
        run: |
          echo "Service ID length: ${#SERVICE_ID}"
          echo "Service ID starts with srv-: $(echo $SERVICE_ID | grep -q '^srv-' && echo 'yes' || echo 'no')"
        env:
          SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
      
      - name: Trigger deployment
        uses: sws2apps/render-deployment@main
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
          multipleDeployment: false